Creating DataFrames ref->2.4

In [5]:
import pandas as pd
import numpy as np

data = np.random.random(size=(5,3))
print(data)
df = pd.DataFrame(data=data, columns=["A", "B", "C"])
df

[[0.25424758 0.30407172 0.01141418]
 [0.67021444 0.53679424 0.42509177]
 [0.4212719  0.78896205 0.3842341 ]
 [0.62160047 0.1747986  0.62351314]
 [0.94564223 0.557511   0.26835834]]


A         B         C
0  0.254248  0.304072  0.011414
1  0.670214  0.536794  0.425092
2  0.421272  0.788962  0.384234
3  0.621600  0.174799  0.623513
4  0.945642  0.557511  0.268358

In [7]:
df = pd.DataFrame(data={"A": [1, 2, 3], "B": ["Sam", "Alex", "Jhon"]})
df

A     B
0  1   Sam
1  2  Alex
2  3  Jhon